name: multi-deployment

on:
  push:
    branches:
      - main
      - dev
      - test

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            environment: production
          - branch: dev
            environment: development
          - branch: test
            environment: test

    environment:
      name: ${{ matrix.environment }}
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4

      - name: Show environment
        run: echo "Deploying branch '${{ github.ref_name }}' to '${{ matrix.environment }}'"

      - name: inject environment name to index.html
        run: |
          sed -i "s|\${ENVIRONMENT}|${{ matrix.environment }}|g" project/index.html

      - name: Upload files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./project

      - id: deployment
        uses: actions/deploy-pages@v4

